name: Build Test
on:
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"
  pull_request:
    paths-ignore:
      - "**.md"
      - "renovate.json"
  workflow_dispatch:

jobs:
  build-test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Build with Java 8
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          cache: "maven"
      - run: java -version
      - run: mvn --version
      - run: mvn -B package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: /home/runner/work/EnderChestPlus/EnderChestPlus/target/
